apiVersion: ramauthenticator.k8s.alibabacloud/v1alpha1
kind: RAMIdentityMapping
metadata:
  name: example-name
spec:
  # RAM Role ram-name is RAM Role nme
  # arn: acs:ram::<your-master-user-id>:role/<ram-name> # replace <your-master-user-id> by master user id for your aliyun account and replace <ram-name> by your RAM role name
  # RAM User ram-name is RAM User name                  
  arn: acs:ram::<your-master-user-id>:user/<ram-name>   # replace <your-master-user-id> by master user id for your aliyun account and replace <ram-name> by your RAM user name
  username: <ram-name>                                  # replace <ram-name> by your RAM user/role name
  groups:
  - system:users
