name: Test

on:
  push:
  pull_request:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.41

  releaser-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
        env:
          GOPATH: ${{ env.HOME }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --snapshot --rm-dist --skip-publish
        env:
          GOPATH: ${{ env.HOME }}

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
      env:
        GOPATH: ${{ env.HOME }}

    - name: Build
      run: make build

    - name: Test
      run: make test
